### ISSUE TITLE
USER STORY: Registration and login

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#1]
EPIC Account

As a **user** I can **create an account by providing my email address and a password** so that **I can register and log in to the application.**

**Acceptance criteria**
- [x] The user can navigate to a registration page.
- [x] The user must enter a valid email address and a password.
- [x] After registration, the user can log in using their credentials.

**Tasks**
- [x] #26
- [x] #27
- [x] #28
- [x] Test registration and login

**Comment by andersganander** [comment]
Added basic functionality, but styling has to be added later
