### ISSUE TITLE
USER STORY: Summary of expenses

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#10]
EPIC Subscriptions

As a **user**, I can **see a summary of my total monthly expenses for subscriptions**, so that **I can budget my expenses more effectively.**

**Acceptance critera**
- [x] A brief summary is shown above the subscription list
- [x] The user has access to a summary page where total monthly costs are displayed.
- [x] The summary page is automatically updated when new subscriptions are added or existing ones are modified.
- [x] The overview shows a breakdown of costs by category, if applicable.
- [ ] If a user has no subscriptions, a message will be shown.

**Tasks**

- [x] Add a very short summary to the left of the icons (or on a separate row)
- [x] Add new page for the summary
- [x] Add view for the new page
- [x] Add logic for retrieveng the data and calculating total cost and monthly cost per category

**Comment by andersganander** [comment]
Added summary in row above subscription list 
Added subscriptions_summary page with a table that contains data for each used category
Added icon with link to subscriptions summary page
Added `subscriptions_summary_view ` with logic for retrieving data and calculating the summary

Last acceptance criteria is not met yet, due to bug #48
