### ISSUE TITLE
USER STORY: Expiry date reminder

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#11]
EPIC <epic>

As a **user**, I can **receive reminders when a subscription is nearing its expiry date**, so that **I can decide whether to continue the subscription or not.**

**Acceptance critera**
- [ ] The system automatically sends a reminder via email and/or in the application 7 days before a subscription is renewed.
- [ ] The reminder includes details about the subscription such as name, cost, and renewal date.
- [ ] The user can set or cancel reminders in a reminder form.

**Tasks**

**Comment by andersganander** [comment]
This user story is deprecated since the expiry date field has been removed. It is replaced by a user story for managing user-defined reminders (#12 )
