### ISSUE TITLE
USER STORY: Add custom reminder

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#12]
EPIC Reminders

As a **user**, I can **create a reminder for a subscription that will be shown on a specific date**, so that **can decide whether to cancel or keep a subscription.**

**Acceptance criteria**
- [x] There will be fields for editing reminder date and reminder message in the edit subscription form
- [x] When the reminder date has passed the message will be shown in the subscription list and in the subscription detail view
- [x] The reminder includes the message that was added when the reminder was created
- [x] The user can change and delete reminders in the dit subscription form 

**Tasks**
- [x] Add icons in subscription list to indicate if there's a reminder
- [x] Add icons in subscription list to indicate if there's a message (if today > reminder date )
- [x] Mark the reminder message in the subscription detail view if there's a message (today > reminder date)
- [x] Style edit form and add delete buttons for reminder date and message

**Comment by andersganander** [comment]
Added icon for reminder in subscription header in subscription list
Added logic for changing color of reminder icon if the subscription is active and there is a upcoming reminder
Added logic for changing the reminder icon when the reminder is triggered
Added logic for changing background color of message in subscription detail view when the reminder is triggered
Added button for clearing reminder date and reminder message in subscription edit form
