### ISSUE TITLE
USER STORY: Manage users

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#2]
EPIC Account

As a **administrator** I can **view, edit, and delete user accounts** so that **I can manage access to the application**

**Acceptance critera**

- [ ] The administrator has a dashboard to view all registered users.
- [x] The dashboard allows the administrator to edit user details and delete user accounts.
- [x] Any changes made by the administrator are logged for audit purposes.

**Tasks**
