### ISSUE TITLE
USER STORY: Manage services

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#3]
EPIC Services

As a **administrator** I can **add, edit, and delete services** so that **I can manage the list of available subscription services**

**Acceptance critera**
- [x] The administrator has access to a management interface where they can see a list of all services.
- [x] The interface includes options to add a new service, edit existing services, and delete services.
- [x] Changes are reflected immediately in the user interface once they are made.

**Tasks**

- [x] Create model for services
- [x] Add services to admin
- [x] Add data (services)

**Comment by andersganander** [comment]
All three tasks implemented
