### ISSUE TITLE
USER STORY: Menu

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#39]
EPIC Navigation

As a **user** I can **navigate the web site using a menu** so that **i can easily find the information i am looking for**

**Acceptance critera**

- [x] When entering the web site a menu is shown with menu options
- [x] At least one option should have a corresponding page
- [x] When a menu option is chosen the corresponding page is shown

**Tasks**

- [x] Create a base.html template that includes a menu, footer and room for block content
- [x] Adjust the list.html so it uses the base template
- [x] Add options in the menu for Subscriptions, Reminders, Services
- [x] Implement the Subscriptions option so that the subscription list is shown when the option is chosen

**Comment by andersganander** [comment]
Added base.html (including links to materialize css)
Added navbar in base.html
Added menu options home, subscriptions,reminders, services
Linked menu option for subscriptions to the subscription list page
Linked menu option service to new page service.html 
Adjusted list.html and service.html to extend base.htm
