### ISSUE TITLE
USER STORY: View a subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#40]
EPIC Subscriptions

As a **user** I can **wiew the details of a subscription** so that **i can decide if i want to keep it**

**Acceptance critera**
- [x] In the subscription list there will be an intuitive way to click on a subscription to see the details
- [x] When a subscription is clicked the details will be shown
- [x] The user will not be able to do any changes to the shown data 

**Tasks**
- [x] Update the subscription list so that it uses googles materialize framework
- [x] Show each subscription in a collapsible component with the category, service name, and price in the header and the rest of the details in the body
- [x] update url mapping if needed

**Comment by andersganander** [comment]
Added new page subscription_list to replace list.html
Added style for materialize collapsible in base.html (temporarily)
Added script for materialize in base.html (temporarily)
Added code for collapsible in subscription_list.html
