### ISSUE TITLE
USER STORY: Make subscription inactive

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#45]
EPIC <subscriptions>

As a **user** I can **make a subscription inactive instead of deleting it** so that **i can make it active again**

**Acceptance critera**
- [x] In the subscription detail (or in the edit form) view there will be a switch to make the subscription inactive
- [x] When the switch is changed , the database will be updated
- [x] When the switch is off the the subscription will be marked as inactive in subscription list
- [x] When the subscription is inactive it will be marked as inactive in subscription detail
- [ ] When the subscription is inactive it will still be editable 

**Tasks**

- [x] Change styling in subscription list
- [x] Change styling in subscription detail

**Comment by andersganander** [comment]
- Changed styling for subscription list
-   Grey text when subscription is inactive
-   Red unchecked radio button when subscription is active
-   Green checked radio button when subscription is active
- Changed styling för subscription detail
-   Light grey background color when subscription is inactive
-   Light red background color for No
-   Light green background color for Yes
