### ISSUE TITLE
USER STORY: Add authentication

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#49]
EPIC <Accounts>

As a **site owner** I want to **make sure that the user is logged in to access subscription related functionality** so that **the security and integrity of user data is maintained**

**Acceptance criteria**
- [ ] 

**Tasks**
- [ ] Style login page
- [ ] Change url structure
- [ ] Make sure the user is logged in when he/she wants to access any page other than About

**Comment by andersganander** [comment]
Added allauth templates
Changed styleing for login, logout and signup pages
Changed url mapping for login and logout redirects
Added links in base.html and logic for when to enable/disable them
