### ISSUE TITLE
USER STORY: Add subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#5]
EPIC Subscriptions

As a **user** I can **add a subscription by filling out a form with the name, cost, and renewal date** so that **I can see it in my overview.**

**Acceptance critera**
- [x] The user has an "Add" button or link on the main page.
- [x] A form is displayed where the user can choose the service from a list, enter cost and renewal date.
- [x] A confirmation is shown when a subscription is saved.

**Tasks**
- [x] Add new view
- [x] Add button to the subscription list page
- [x] Add simple html (including a form) for add subscription page
- [x] add logic for updating database
- [x] add feedback to user when subscription is added
- [x] add url routing

**Comment by andersganander** [comment]
Added class SubscriptionForm in models.py
Added add_subscription.html with form and link back to list
Added subscription_form_view where form data is handled and saved
Added message when form data was saved
Added link i list.html to add subscription page
Added routing in urls.py
