### ISSUE TITLE
USER STORY: Add custom service name for subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#50]
EPIC <Subscriptions>

As a **user** I can **add my own service name when i add a subscription** so that **i can track all my subscriptions even if they  are not in the service list**

**Acceptance critera**
- [x] When adding a subscription there will be a field for service name, which will have the chosen service's name as default
- [x] When a service name is changed by a user, that name will be shown i subscription list and subscription detail
- [x] In the subscription edit form the service name will be editable
- [x] The name will not be changed for the service, just for the subscription    

**Tasks**

- [x] Add field in model
- [x] Add field in form
- [x] Add logic in template to populate field with service name
- [x] Makemigrations, migrate
- [x] Change so that service name is retrieved from subscription where it's used (subscription list, subscription detail, subscription_edit etc)

**Comment by andersganander** [comment]
Added field subscription_name
Migrated data model
Changed from `subscription.service.name` to `subscription.subscription_name `in several places
Added field for `subscription.service.name` in subscription detail
Added code in javascript to set the value of subsscription name field to the value of the selected service
