### ISSUE TITLE
USER STORY: Mail reminder

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#51]
EPIC <epic>

As a **user** I want to **receive a mail with my reminder note** so that **I don't have to log in to the application every day**

**Acceptance critera**
- [ ] Every day a job will execute and check if there are any reminders to be sent
- [ ] If there is a reminder for the current date and the subscriber has a registered e-mail-adress a mail will be sent 

**Tasks**
- [ ] Create a python job that checks all subscribtions reminder dates
- [ ] Add field in subscription which will be used for checkling if a reminder mail has been sent 
- [ ] Schedule the job so that it is executed once (or twice) a day.  
- [ ] Configure mail settings

**Comment by andersganander** [comment]
Configured mail settings i Heroku, config vars
Scheduled job in Heroku to run every 10 minutes now during development phase, will be changed to once a day.
