### ISSUE TITLE
USER STORY: Cancel log out

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#55]
EPIC Accounts

As a **user** I can **cancel log out** so that **i don't need to log in again if i change my mind**

**Acceptance criteria**
- [x]  On the log out page that is shown when the log out link in the nav bar is clicked there will be a red cancel button
- [x] When the cancel button is clicked the subscription list will be showed

**Tasks**
- [x] Add cancel button in log out window

**Comment by andersganander** [comment]
Implemented tasks
