### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#58]
EPIC <Navigation>

As a **user** I can **read about the application on the start page** so that **i understand how to use it**

**Acceptance critera**
- [ ] The start page should contain information about the application and how to use it, with links to login and sign up

**Tasks**
- [ ] Add a index.html page
- [ ] Edit url mapping

**Comment by andersganander** [comment]
Requirements were changed. Instead of having a start page, there would be a about page that could be accessed without having to login. But it would not be the start page since it would require extra clicks for returning users who just want to login.

- [ ] Added about.html (need to be styled and updated)
- [ ]  Added links to About in nav bar
- [ ] Added view for about
- [ ] Added routes in `urls.py`
