### ISSUE TITLE
USER STORY: View subscriptions

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#6]
EPIC Subscriptions

As a **user** I can **see a list of all my subscriptions** so that **i get an overview**

**Acceptance critera**

- [x] A list of the logged in users subscriptions is displayed on the main page.
- [x] The list includes the name, cost, and renewal date for each subscription.
- [x] If no subscriptions are present, a message indicating this is displayed.

**Tasks**

- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
