### ISSUE TITLE
USER STORY: Add mail-adress for reminder

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#65]
EPIC <Reminders>

As a **user** I can **add a mail adress that the reminder will be sent to** so that **i can receive a mail reminder even if i don't have a mail adress on my account **

**Acceptance criteria**
- [ ] There will be a mail field "Reminder e-mail" in the edit form and in the detail view
- [ ] If the user has a registered e-mail, that will be used as default
- [ ] The mail will be sent to the reminder e-mail

**Tasks**
- Add field in subscription model
- Update view
- Update send_reminder_email

**Comment by andersganander** [comment]
Added reminder_email to model
Migrated new model
Updated subscriptions_view and subscription_edit_view
Updated subscription_list.html
Updated send_reminder_email
