### ISSUE TITLE
USER STORY: Edit subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#7]
EPIC Subscriptions

As a **user** I can **edit a subscription** so that **I can update with relevant information**

**Acceptance critera**
- [ ] Each entry in the subscription list has an "Edit" button.
- [ ] When "Edit" is selected, a form with the existing details is displayed for the user to edit.
- [ ] Changes can be saved or canceled.
- [ ] A confirmation is shown when a subscription is saved.

**Tasks**
