### ISSUE TITLE
USER STORY: Delete Subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#8]
EPIC Subscriptions

As a user i can delete a subscription from the list so that

**Acceptance critera**
- [x] Each entry in the subscription list has a "Delete" button.
- [x] When "Delete" is selected, a confirmation prompt appears to prevent accidental deletion.
- [x] The subscription is removed from the list once confirmation is approved.

**Tasks**
- [x] Add delete button in subscription detail
- [x] Add code for opening modal (or separate window) and ask user to confirm delete or cancel
- [x] Add view for deleting a subscription

**Comment by andersganander** [comment]
Added delete button in subscription detail 
Added modal with unique id for each subscription
Added `subscription_delete_view`  
Added feedback message when subscription was deleted
