### ISSUE TITLE
TODO Lördag

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#83]
- [x] Uppdatera ERD
- [x] Uppdatera Wireframes
- [x] Skapa readme med rubriker
- [ ] ~~Skapa Ett par unit-tester~~
- [ ] ~~Gör färdigt feature-delen i testing md~~
- [ ] ~~Gör färdigt test-protokoll (admin-tester)~~ TODO Söndag
- [x] Fortsätt uppdatera readme
