### ISSUE TITLE
TODO Söndag

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#84]
- [x] 500.html
- [ ] Describe features in readme
- [x] Validate python and describe i testing.md
- [x] Validate all pages with lighthouse
- [x] Validate css
- [ ]  Describe bugs
