### ISSUE TITLE
USER STORY: Categorize subscription

### ISSUE THREAD

**Issue by andersganander** [andersganander/Subscription_manager#9]
EPIC Subscription

As a **user**, I can **categorize my subscriptions** so that **I can view costs for each category separately.**

**Acceptance critera**
- [x] The user can change category (from the default category) when adding a new subscription or editing an existing one.
- [x] In the details view the category that the user selected will be shown instead of the default category
- [x] In the summary view the user selected categorys will be used

**Tasks**

- [ ] Set category in subscription to the default category for the service when the subscription is added

**Comment by andersganander** [comment]
Implemented
